# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

# Filesystem ID
ceph_mgr_fsid: "{{ ceph_fsid }}"

ceph_mgr_modules:
  - name: diskprediction_local
  - name: dashboard
  - name: prometheus
  - name: iostat
